<a href="https://colab.research.google.com/github/Anmoljigupta/codsoft/blob/main/Untitled15.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [ ]:
credit_card_data = pd.read_csv('/content/creditcard.csv')

In [ ]:
credit_card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [ ]:
credit_card_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
3968,3617,1.134592,0.252051,0.488592,0.799826,-0.264819,-0.369918,-0.243365,0.049761,1.210818,...,-0.351115,-0.851463,0.186169,0.092463,0.020015,0.057976,-0.046611,0.012562,13.99,0.0
3969,3621,-1.338671,1.080974,1.291196,0.719258,0.101320,0.053896,0.001297,-0.917575,1.638510,...,0.498030,-0.483932,0.037686,0.053566,-0.560078,0.230423,-0.119911,0.321847,27.43,0.0
3970,3622,-0.339728,-2.417449,0.975517,2.537995,-1.720361,0.863005,0.032965,0.026764,2.487139,...,0.391639,0.264432,-0.735031,0.450594,0.310022,-0.231357,-0.049872,0.153526,730.32,0.0
3971,3623,-0.368639,0.947432,1.707755,0.932092,0.292956,0.189100,0.499330,0.132466,0.779412,...,-0.119045,0.056665,-0.172703,0.170073,0.139605,-0.420518,0.033794,0.005996,6.87,0.0
3972,3624,-0.663445,1.162921,1.508050,0.549405,0.231377,-0.106041,0.817977,-0.387026,1.488054,...,-0.420337,-0.361357,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

data set information

In [ ]:
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3973 entries, 0 to 3972
Data columns (total 31 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Time    3973 non-null   int64
 1   V1      3973 non-null   float64
 2   V2      3973 non-null   float64
 3   V3      3973 non-null   float64
 4   V4      3973 non-null   float64
 5   V5      3973 non-null   float64
 6   V6      3973 non-null   float64
 7   V7      3973 non-null   float64
 8   V8      3973 non-null   float64
 9   V9      3973 non-null   float64
 10  V10     3973 non-null   float64
 11  V11     3973 non-null   float64
 12  V12     3973 non-null   float64
 13  V13     3973 non-null   float64
 14  V14     3973 non-null   float64
 15  V15     3973 non-null   float64
 16  V16     3973 non-null   float64
 17  V17     3973 non-null   float64
 18  V18     3973 non-null   float64
 19  V19     3973 non-null   float64
 20  V20     3973 non-null   float64
 21  V21     3973 non-null   float64
 22  V22     3973 non-null   float64
 23  V23     3972 non-null   float64
 24  V24     3972 non-null   float64
 25  V25     3972 non-null   float64
 26  V26     3972 non-null   float64
 27  V27     3972 non-null   float64
 28  V28     3972 non-null   float64
 29  Amount  3972 non-null   float64
 30  Class   3972 non-null   float64
dtypes: float64(30), int64(1)
memory usage: 962.3 KB

checking the number of missing value in each column

In [ ]:
credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       1
V24       1
V25       1
V26       1
V27       1
V28       1
Amount    1
Class     1
dtype: int64

distribution of lrgit transaction and fraudulent transaction

In [ ]:
credit_card_data['Class'].value_counts()

0.0    3970
1.0       2
Name: Class, dtype: int64

this dataset is highly unblanced

0--> Normal Transaction
1--> fraudulent transaction

separating the data for analysis

In [ ]:
legit = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class == 1]

In [ ]:
print(legit.shape)
print(fraud.shape)

(3970, 31)
(2, 31)

statistical measures of the data

In [ ]:
legit.Amount.describe()

count    3970.000000
mean       64.899597
std       213.612570
min         0.000000
25%         2.270000
50%        12.990000
75%        54.990000
max      7712.430000
Name: Amount, dtype: float64

In [ ]:
fraud.Amount.describe()

count      2.000000
mean     264.500000
std      374.059487
min        0.000000
25%      132.250000
50%      264.500000
75%      396.750000
max      529.000000
Name: Amount, dtype: float64

compare the values for both transaction

In [ ]:
credit_card_data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,1638.828463,-0.332459,0.308935,0.837446,0.011432,-0.029468,0.053530,0.147357,-0.071642,0.056211,...,0.059567,0.010282,-0.082957,-0.058743,0.029114,0.095244,-0.012637,0.044658,0.002668,64.899597
1.0,439.000000,-2.677884,-0.602658,-0.260694,3.143275,0.418809,-1.245684,-1.105907,0.661932,-1.520521,...,1.114625,0.589464,0.200214,0.455377,0.013198,0.162159,0.016239,0.004186,-0.053756,264.500000

#under-sampling

build a sample dataset containing similar distribuation of normal transaction and fraudulent transactions

Number of fraudulent Transaction-->492

In [ ]:
legit_sample = legit.sample(n=492)

Concatenating two Dataframes

In [ ]:
new_dataset = pd.concat([legit_sample, fraud], axis=0)

In [ ]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
71,46,-0.378245,0.732925,-0.120154,0.185755,2.594269,3.797183,0.059088,0.976768,-0.412661,...,-0.107582,-0.157140,-0.194659,1.013897,0.145503,-0.237620,0.411372,0.202788,11.45,0.0
1243,957,0.082304,0.479129,0.951227,0.707433,-0.227498,-0.096774,0.122413,0.129038,0.545991,...,0.115344,0.546633,0.111999,0.104137,-1.179282,0.323376,0.061304,0.158291,0.95,0.0
3585,3066,-0.938912,0.667940,0.527285,3.380407,0.484574,0.320893,-0.493156,0.734189,-1.068349,...,0.226437,0.604509,0.076179,-0.047035,-1.295099,0.085923,0.057840,0.180771,7.58,0.0
1900,1467,-1.629826,1.326529,0.906349,-0.800461,-0.283720,-0.383247,0.201000,0.585984,0.253948,...,-0.197779,-0.385304,-0.066693,0.022864,0.141284,0.385286,0.250911,0.192462,5.00,0.0
1517,1187,1.173891,0.045059,0.101328,0.480990,-0.187947,-0.143309,-0.250114,0.235604,0.150448,...,-0.251652,-0.863099,0.126242,-0.412989,0.073215,0.134016,-0.028113,0.010395,10.97,0.0

In [ ]:
new_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
217,143,-2.143458,2.107826,0.213152,1.282217,-0.732558,0.023589,-0.073256,0.924143,-0.356988,...,0.044641,0.345346,0.013233,0.117188,0.012406,-0.288531,-0.473894,-0.184488,39.95,0.0
2943,2490,-3.461034,-3.011263,2.365882,0.280613,3.720816,-2.418969,-1.281954,-0.111655,-0.051599,...,-0.201940,-0.635242,-0.076881,0.236561,0.081227,-0.041449,-0.446936,-0.052875,9.47,0.0
2704,2243,1.226045,-0.022482,0.506098,0.855552,-0.672954,-0.741619,-0.106891,-0.062205,0.662056,...,-0.245534,-0.594098,0.026694,0.394406,0.408814,0.272851,-0.031415,0.010616,9.44,0.0
541,406,-2.312227,1.951992,-1.609851,3.997906,-0.522188,-1.426545,-2.537387,1.391657,-2.770089,...,0.517232,-0.035049,-0.465211,0.320198,0.044519,0.177840,0.261145,-0.143276,0.00,1.0
623,472,-3.043541,-3.157307,1.088463,2.288644,1.359805,-1.064823,0.325574,-0.067794,-0.270953,...,0.661696,0.435477,1.375966,-0.293803,0.279798,-0.145362,-0.252773,0.035764,529.00,1.0

In [ ]:
new_dataset['Class'].value_counts

<bound method IndexOpsMixin.value_counts of 71      0.0
1243    0.0
3585    0.0
1900    0.0
1517    0.0
       ...
217     0.0
2943    0.0
2704    0.0
541     1.0
623     1.0
Name: Class, Length: 494, dtype: float64>

In [ ]:
new_dataset.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,1670.367886,-0.324598,0.340985,0.757672,-0.000462,-0.081363,0.150770,0.136856,-0.026029,0.024616,...,0.065637,0.046380,-0.058066,-0.054433,0.038802,0.079160,-0.033981,0.030639,-0.013953,67.940854
1.0,439.000000,-2.677884,-0.602658,-0.260694,3.143275,0.418809,-1.245684,-1.105907,0.661932,-1.520521,...,1.114625,0.589464,0.200214,0.455377,0.013198,0.162159,0.016239,0.004186,-0.053756,264.500000

Splitting the data info Features & Targets

In [ ]:
X = new_dataset.drop(columns='Class', axis=1)
Y = new_dataset['Class']

In [ ]:
print(X)

      Time        V1        V2        V3        V4        V5        V6  \
71      46 -0.378245  0.732925 -0.120154  0.185755  2.594269  3.797183
1243   957  0.082304  0.479129  0.951227  0.707433 -0.227498 -0.096774
3585  3066 -0.938912  0.667940  0.527285  3.380407  0.484574  0.320893
1900  1467 -1.629826  1.326529  0.906349 -0.800461 -0.283720 -0.383247
1517  1187  1.173891  0.045059  0.101328  0.480990 -0.187947 -0.143309
...    ...       ...       ...       ...       ...       ...       ...
217    143 -2.143458  2.107826  0.213152  1.282217 -0.732558  0.023589
2943  2490 -3.461034 -3.011263  2.365882  0.280613  3.720816 -2.418969
2704  2243  1.226045 -0.022482  0.506098  0.855552 -0.672954 -0.741619
541    406 -2.312227  1.951992 -1.609851  3.997906 -0.522188 -1.426545
623    472 -3.043541 -3.157307  1.088463  2.288644  1.359805 -1.064823

            V7        V8        V9  ...       V20       V21       V22  \
71    0.059088  0.976768 -0.412661  ...  0.315572 -0.107582 -0.157140
1243  0.122413  0.129038  0.545991  ... -0.221124  0.115344  0.546633
3585 -0.493156  0.734189 -1.068349  ...  0.012961  0.226437  0.604509
1900  0.201000  0.585984  0.253948  ...  0.080721 -0.197779 -0.385304
1517 -0.250114  0.235604  0.150448  ... -0.224377 -0.251652 -0.863099
...        ...       ...       ...  ...       ...       ...       ...
217  -0.073256  0.924143 -0.356988  ... -0.112866  0.044641  0.345346
2943 -1.281954 -0.111655 -0.051599  ...  0.073556 -0.201940 -0.635242
2704 -0.106891 -0.062205  0.662056  ... -0.198482 -0.245534 -0.594098
541  -2.537387  1.391657 -2.770089  ...  0.126911  0.517232 -0.035049
623   0.325574 -0.067794 -0.270953  ...  2.102339  0.661696  0.435477

           V23       V24       V25       V26       V27       V28  Amount
71   -0.194659  1.013897  0.145503 -0.237620  0.411372  0.202788   11.45
1243  0.111999  0.104137 -1.179282  0.323376  0.061304  0.158291    0.95
3585  0.076179 -0.047035 -1.295099  0.085923  0.057840  0.180771    7.58
1900 -0.066693  0.022864  0.141284  0.385286  0.250911  0.192462    5.00
1517  0.126242 -0.412989  0.073215  0.134016 -0.028113  0.010395   10.97
...        ...       ...       ...       ...       ...       ...     ...
217   0.013233  0.117188  0.012406 -0.288531 -0.473894 -0.184488   39.95
2943 -0.076881  0.236561  0.081227 -0.041449 -0.446936 -0.052875    9.47
2704  0.026694  0.394406  0.408814  0.272851 -0.031415  0.010616    9.44
541  -0.465211  0.320198  0.044519  0.177840  0.261145 -0.143276    0.00
623   1.375966 -0.293803  0.279798 -0.145362 -0.252773  0.035764  529.00

[494 rows x 30 columns]

In [ ]:
print(Y)

71      0.0
1243    0.0
3585    0.0
1900    0.0
1517    0.0
       ...
217     0.0
2943    0.0
2704    0.0
541     1.0
623     1.0
Name: Class, Length: 494, dtype: float64

Split the data info Training data & Testing data

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.2, stratify=Y, random_state=2)

In [ ]:
print(X.shape, X_train.shape, X_test.shape)

(494, 30) (395, 30) (99, 30)

MODEL TRAINING

Logistic Regression

In [ ]:
model = LogisticRegression()

training the logistic regression model with training data

In [ ]:
model.fit(X_train, Y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

MODEL EVALUATION

Accuracy Score

accuracy on training data

In [ ]:
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [ ]:
print('Accuracy on trainig data : ', training_data_accuracy)

Accuracy on trainig data :  1.0

#accuracy on test data

In [ ]:
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [ ]:
print('Accuracy score on Test Datab : ', test_data_accuracy)

Accuracy score on Test Datab :  1.0